<?php

use Illuminate\Database\Seeder;

class UrlsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('urls')->insert([
            ['categoria_id'=> '3', 'loja_id'=> '15', 'url'=> 'http://m.costco.com.mx/view/c/linea-blanca/linea-blanca-refrigeradores-y-congeladores/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '8', 'url'=> 'http://m.ricardoeletro.com.br/Loja/Eletrodomesticos/Refrigerador/256-270', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '26', 'url'=> 'http://www.alkosto.com/electro/neveras', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '4', 'url'=> 'http://www.bestbuy.com.mx/productos/hogar/refrigeradores.html?cat=1290', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '3', 'url'=> 'http://www.casasbahia.com.br/Eletrodomesticos/GeladeiraeRefrigerador/?Filtro=C13_C14', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '12', 'url'=> 'http://www.claroshop.com/categoria/16201/refrigeradores-y-congeladores/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '39', 'url'=> 'http://www.comandato.com/electrodomesticos/refrigeracion?O=OrderByReleaseDateDESC', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '15', 'url'=> 'http://www.costco.com.mx/view/c/linea-blanca/linea-blanca-refrigeradores-y-congeladores/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '17', 'url'=> 'http://www.elpalaciodehierro.com/hogar/hogar-linea-blanca/hogar-lineablanca-refrigeradores.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '27', 'url'=> 'http://www.exito.com/Electrohogar-Grandes_Electrodomesticos-Neveras/_/N-2ai7?showMoreIds=109170', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/Eletrodomesticos/GeladeiraeRefrigerador/?Filtro=C13_C14&nid=200579', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '28', 'url'=> 'http://www.falabella.com.co/falabella-co/category/cat1040982/Neveras', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat40754/Refrigeracion', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '21', 'url'=> 'http://www.falabella.com/falabella-cl/category/cat4074/No-Frost', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '30','url'=>  'http://www.fravega.com/heladeras-freezers-y-cavas', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '36', 'url'=> 'http://www.gollotienda.com/productos/linea-blanca/refrigeracion/refrigeradoras.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '6', 'url'=> 'http://www.magazineluiza.com.br/geladeira-refrigerador/eletrodomesticos/s/ed/refr/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '4', 'url'=> 'http://www.pontofrio.com.br/Eletrodomesticos/GeladeiraeRefrigerador/?Filtro=C13_C14&nid=201068', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'18', 'url'=> 'http://www.sears.com.mx/categoria/15523/refrigeracion/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'25', 'url'=> 'http://www.tiendasjumbo.co/electrodomesticos/refrigeraci%C3%B3n', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'37', 'url'=> 'https://hifi.com.do/productos/4/price-asc', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'3', 'url'=> 'https://m.casasbahia.com.br/#/departamentos/13_14', 'status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>'6', 'url'=> 'https://m.magazineluiza.com.br/geladeira-refrigerador/eletrodomesticos/s/ed/refr/', 'status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>'4', 'url'=> 'https://m.pontofrio.com.br/#/departamentos/13_14', 'status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>'7', 'url'=> 'https://m.walmart.com.br/categoria/eletrodomesticos/refrigeracao/?fq=C:144/7952/&PS=20', 'status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>'22', 'url'=> 'https://simple.ripley.cl/electrohogar/refrigeracion', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'24', 'url'=> 'https://www.abcdin.cl/tienda/es/abcdin/linea-blanca/refrigeradores#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'16', 'url'=> 'https://www.amazon.com.mx/b/?node=16354941011', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'1', 'url'=> 'https://www.americanas.com.br/categoria/eletrodomesticos/geladeira-refrigerador/#/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'9', 'url'=> 'https://www.carrefour.com.br/refrigerar?crfint=m-links|eletrodomesticos|refrigerar|2|refrigerar|0','status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'19', 'url'=> 'https://www.elektra.com.mx/linea-blanca/refrigeradores-y-congeladores/refrigeradores', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'17', 'url'=> 'https://www.elpalaciodehierro.com/hogar/hogar-linea-blanca/hogar-lineablanca-refrigeradores.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'10', 'url'=> 'https://www.fastshop.com.br/loja/eletrodomesticos/pra-sua-cozinha/refrigerador-geladeira', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'29', 'url'=> 'https://www.garbarino.com/productos/heladeras-y-freezers/4290', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'13', 'url'=> 'https://www.liverpool.com.mx/tienda/refrigeradores/cat4170025', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'35', 'url'=> 'https://www.panafoto.com/categorias/hogar.html?cat=168', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'23', 'url'=> 'https://www.paris.cl/tienda/es/paris/search/linea-blanca-refrigeracion-todos-los-refrigeradores', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '32', 'url'=> 'https://www.ribeiro.com.ar/browse/Heladeras-Cocina-y-Lavado-Heladeras-Con-Freezer-No-frost/_/N-1kfjx94', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '20', 'url'=> 'https://www.sams.com.mx/linea-blanca/refrigeradores-y-congeladores', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '2', 'url'=> 'https://www.submarino.com.br/categoria/eletrodomesticos/geladeira-refrigerador/#/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '2', 'url'=> 'https://www.submarino.com.br/categoria/eletrodomesticos/geladeira-refrigerador/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '38', 'url'=> 'https://www.tiendamonge.com/linea-blanca?specs=428', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=> '7', 'url'=> 'https://www.walmart.com.br/categoria/eletrodomesticos/refrigeracao/?fq=C:144/7952/&PS=20', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '8', 'url'=> 'http://m.ricardoeletro.com.br/Loja/Celulares-e-Telefones/Smartphones/44-491', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=>'26','url'=>  'http://www.alkosto.com/telefonos-celulares/celulares-libres', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '4', 'url'=> 'http://www.bestbuy.com.mx/productos/tablets-y-celulares/telefonos-celulares.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=>  '12','url'=>  'http://www.claroshop.com/categoria/16002/celulares/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '39','url'=>  'http://www.comandato.com/tecnologia/telefonia/celulares', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '17', 'url'=> 'http://www.elpalaciodehierro.com/tecnologia/tecnologia-celulares.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '27','url'=>  'http://www.exito.com/Tecnologia-Celulares_y_accesorios/_/N-2b5r', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/TelefoneseCelulares/Smartphones/?Filtro=C38_C326&nid=200740', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '28', 'url'=> 'http://www.falabella.com.co/falabella-co/category/cat1660941/Celulares-Libres', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat760706/Smartphones', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '21', 'url'=> 'http://www.falabella.com/falabella-cl/category/cat720161/Smartphones', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '30', 'url'=> 'http://www.fravega.com/celulares/celulares-liberados', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '36', 'url'=> 'http://www.gollotienda.com/productos/telefonia/celulares.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '6', 'url'=> 'http://www.magazineluiza.com.br/smartphone/celulares-e-smartphones/s/te/tcsp/', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '4', 'url'=> 'http://www.pontofrio.com.br/TelefoneseCelulares/Smartphones/?Filtro=C38_C326', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '18', 'url'=> 'http://www.sears.com.mx/categoria/4550/telefonia/','status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '25', 'url'=> 'http://www.tiendasjumbo.co/tecnologia/celulares-y-tablets/celulares', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '3', 'url'=> 'https://m.casasbahia.com.br/#/departamentos/38_326', 'status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '6', 'url'=> 'https://m.magazineluiza.com.br/smartphone/celulares-e-smartphones/s/te/tcsp/', 'status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '4', 'url'=> 'https://m.pontofrio.com.br/#/departamentos/38_326', 'status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '7', 'url'=> 'https://m.walmart.com.br/categoria/telefonia/smartphones/?fq=C:4833/4835/4845/&PS=20', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '24', 'url'=> 'https://www.abcdin.cl/tienda/es/abcdin/celulares/smartphones#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '16', 'url'=> 'https://www.amazon.com.mx/b/ref=s9_acss_bw_fb_lensmoun_b2/ref=s9_acss_bw_cg_wire1_1b1/ref=s9_acss_bw_cg_mxceti_1a1_w?_encoding=UTF8&node=9687460011&pf_rd_m=AVDBXBAVVSXLQ&pf_rd_s=merchandised-search-6&pf_rd_r=WVPDE7GV549QCC7FT578&pf_rd_t=101&pf_rd_p=214627', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '1', 'url'=> 'https://www.americanas.com.br/categoria/celulares-e-smartphones/smartphone', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '9', 'url'=> 'https://www.carrefour.com.br/celular-e-smartphone?termo=%3Arelevance&isGrid=true&sort=', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '9', 'url'=> 'https://www.carrefour.com.br/dicas/tecnologia-e-eletronicos/celular-e-smartphone?crfint=hm-tlink|tecnologia-e-eletronicos|telefonia|4|celular-e-smartphone|1', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '31', 'url'=> 'https://www.compumundo.com.ar/productos/smartphones-libres/3757','status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '19', 'url'=> 'https://www.elektra.com.mx/telefonia/celulares/desbloqueados', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '17', 'url'=>  'https://www.elpalaciodehierro.com/tecnologia/tecnologia-celulares.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/tecnologia/tecnologia-celulares.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/tecnologia/tecnologia-celulares.html', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '29', 'url'=> 'https://www.garbarino.com/productos/celulares-libres/4359', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '13', 'url'=> 'https://www.liverpool.com.mx/tienda/ver-todos-los-modelos/cat5070000', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '35', 'url'=> 'https://www.panafoto.com/categorias/celulares-tablets.html?cat=130', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '23', 'url'=> 'https://www.paris.cl/tienda/es/paris/search/tecnologia-celulares-smartphones', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '32', 'url'=> 'https://www.ribeiro.com.ar/browse/celulares-celulares-libres/_/N-1vpfmld', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '20', 'url'=>  'https://www.sams.com.mx/celulares-y-smartphones/celulares/celulares-desbloqueados/_/N-83g', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '2', 'url'=> 'https://www.submarino.com.br/categoria/celulares-e-smartphones/smartphone', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '38', 'url'=> 'https://www.tiendamonge.com/telefonia?specs=409', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'1', 'loja_id'=> '7', 'url'=> 'https://www.walmart.com.br/categoria/telefonia/smartphones/?fq=C:4833/4835/4845/&PS=20', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '8', 'url'=> 'http://m.ricardoeletro.com.br/Loja/TV-e-Video/TV/108-4370', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '34', 'url'=> 'http://simple.ripley.com.pe/tv-y-video/televisores/ver-todo-tv', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '26', 'url'=> 'http://www.alkosto.com/tv', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '26', 'url'=> 'http://www.alkosto.com/tv/televisores', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '3', 'url'=> 'http://www.casasbahia.com.br/tvseacessorios/Televisores/?Filtro=C1_C2', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '12', 'url'=> 'http://www.claroshop.com/categoria/16023/pantallas/', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '39', 'url'=> 'http://www.comandato.com/tecnologia/television-y-video/televisores-led?O=OrderByReleaseDateDESC', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '15', 'url'=> 'http://www.costco.com.mx/view/c/electronica/tv-y-video', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=>  '15', 'url'=> 'http://www.costco.com.mx/view/c/electronica/tv-y-video/televisiones/4K', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '17', 'url'=> 'http://www.elpalaciodehierro.com/tecnologia/tecnologia-tvyvideo/tecnologia-tvyvideo-pantallas.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '27', 'url'=> 'http://www.exito.com/browse/Tecnologia-TV_y_Video-Televisores/_/N-2csn', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/tvseacessorios/Televisores/?Filtro=C1_C2', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '28', 'url'=> 'http://www.falabella.com.co/falabella-co/category/cat1360963/Televisores', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat210477/Televisores', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat6370551/TV-LED', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '21', 'url'=> 'http://www.falabella.com/falabella-cl/category/cat1012/TV', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '30', 'url'=> 'http://www.fravega.com/tv-y-video/tv', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '36', 'url'=> 'http://www.gollotienda.com/productos/pantallas/led.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '6', 'url'=> 'http://www.magazineluiza.com.br/tv-led-plasma-lcd-e-outras/tv-e-video/s/et/peco/', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '4', 'url'=> 'http://www.pontofrio.com.br/tvseacessorios/Televisores/?Filtro=C1_C2', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '18', 'url'=> 'http://www.sears.com.mx/categoria/15466/pantallas/', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '25', 'url'=> 'http://www.tiendasjumbo.co/tecnologia/televisores-y-video/televisores/tvs?ref=LandingTv', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '37', 'url'=> 'https://hifi.com.do/productos/34/price-asc', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '3', 'url'=> 'https://m.casasbahia.com.br/#/departamentos/1_2', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '6', 'url'=> 'https://m.magazineluiza.com.br/smart-tv/tv-e-video/s/et/elit/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '4', 'url'=> 'https://m.pontofrio.com.br/#/departamentos/1_2','status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=>'7', 'url'=> 'https://m.walmart.com.br/categoria/eletronicos/tvs/?fq=C:7240/7242/&PS=20&mm=100', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '24', 'url'=> 'https://www.abcdin.cl/tienda/es/abcdin/tv-audio/televisores-video/televisores-led#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '16', 'url'=> 'https://www.amazon.com.mx/b?ie=UTF8&node=9687950011', 'status'=>'', 'device'=>'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '1', 'url'=> 'https://www.americanas.com.br/categoria/tv-e-home-theater/tv/tv-led', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '9', 'url'=> 'https://www.carrefour.com.br/tv?termo=%3Arelevance&isGrid=true&sort=', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '31', 'url'=> 'https://www.compumundo.com.ar/productos/tv-proyectores/3801', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '19', 'url'=> 'https://www.elektra.com.mx/electronica/tv-y-video', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/tecnologia/tecnologia-tvyvideo/tecnologia-tvyvideo-pantallas.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '10', 'url'=> 'https://www.fastshop.com.br/loja/tv-e-video/tvs-', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '29', 'url'=> 'https://www.garbarino.com/productos/tv-led-y-smart-tv/4342', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '13', 'url'=> 'https://www.liverpool.com.mx/tienda/pantallas/cat480023', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '35', 'url'=> 'https://www.panafoto.com/categorias/tvs.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '23', 'url'=> 'https://www.paris.cl/tienda/es/paris/search/electro-television-todas-las-tv', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '32', 'url'=> 'https://www.ribeiro.com.ar/browse/televisores-audio-foto-y-video-televisores-smart-tv-led/_/N-13nn749', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '20', 'url'=> 'https://www.sams.com.mx/electronica/pantallas', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=>'2', 'url'=> 'https://www.submarino.com.br/categoria/tv-e-home-theater/tv/tv-led', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '38', 'url'=> 'https://www.tiendamonge.com/tv-y-video?specs=408', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '7', 'url'=> 'https://www.walmart.com.br/categoria/eletronicos/tvs/?fq=C:7240/7242/&PS=20&mm=100', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'15', 'url'=> 'http://m.costco.com.mx/view/c/linea-blanca/linea-blanca-lavanderia/lavadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '8', 'url'=> 'http://m.ricardoeletro.com.br/Loja/Eletrodomesticos/Lava-e-Seca/256-706', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4',' loja_id'=> '26','url'=> 'http://www.alkosto.com/electro/lavadoras/lavadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'4', 'url'=> 'http://www.bestbuy.com.mx/productos/hogar/lavadoras-y-secadoras.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '3', 'url'=> 'http://www.casasbahia.com.br/Eletrodomesticos/maquinadelavar/?Filtro=C13_C24', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'12', 'url'=> 'http://www.claroshop.com/categoria/16197/lavadoras-y-secadoras/', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'39', 'url'=> 'http://www.comandato.com/electrodomesticos/lavado-y-secado?O=OrderByReleaseDateDESC', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'15', 'url'=> 'http://www.costco.com.mx/view/c/linea-blanca/linea-blanca-lavanderia/lavadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '17', 'url'=> 'http://www.elpalaciodehierro.com/hogar/hogar-linea-blanca/hogar-lineablanca-lavadoras.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '27', 'url'=> 'http://www.exito.com/Electrohogar-Grandes_Electrodomesticos-Lavadoras_y_Secadoras/_/N-2aie', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/Eletrodomesticos/maquinadelavar/?Filtro=C13_C24&nid=200577', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '28', 'url'=> 'http://www.falabella.com.co/falabella-co/category/cat50714/Lavadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat40662/Lavado', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '21', 'url'=> 'http://www.falabella.com/falabella-cl/category/cat4060/Lavadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '30', 'url'=> 'http://www.fravega.com/lavado', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '36', 'url'=>  'http://www.gollotienda.com/productos/linea-blanca/lavanderia/lavadoras.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '6', 'url'=> 'http://www.magazineluiza.com.br/maquina-de-lavar/eletrodomesticos/s/ed/lava/', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '4', 'url'=> 'http://www.pontofrio.com.br/Eletrodomesticos/maquinadelavar/?Filtro=C13_C24&nid=201069', 'status'=>'', 'device'=>  'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '18', 'url'=> 'http://www.sears.com.mx/categoria/10667/lavado/', 'status'=>'', 'device'=>  'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '25', 'url'=> 'http://www.tiendasjumbo.co/electrodomesticos/lavadoras-y-secadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '37', 'url'=> 'https://hifi.com.do/productos/15/price-asc', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '3', 'url'=> 'https://m.casasbahia.com.br/#/departamentos/13_24', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '6', 'url'=> 'https://m.magazineluiza.com.br/maquina-de-lavar/eletrodomesticos/s/ed/lava/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '4', 'url'=> 'https://m.pontofrio.com.br/#/departamentos/13_24', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '7', 'url'=> 'https://m.walmart.com.br/categoria/eletrodomesticos/lavanderia/?fq=C:144/7953/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '22', 'url'=> 'https://simple.ripley.cl/electrohogar/lavado-y-secado', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '24', 'url'=> 'https://www.abcdin.cl/tienda/es/abcdin/linea-blanca/lavado-secado#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '16', 'url'=> 'https://www.amazon.com.mx/b/?node=16354823011', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>  '1','url'=>  'https://www.americanas.com.br/categoria/eletrodomesticos/maquina-de-lavar-e-tanquinho/maquina-de-lavar', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '9', 'url'=> 'https://www.carrefour.com.br/lavar-e-secar-roupa?crfint=m-links|eletrodomesticos|lavar-e-secar-roupa|3|lavar-e-secar-roupa|0', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '19', 'url'=> 'https://www.elektra.com.mx/linea-blanca/lavado-y-secado/lavadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/hogar/hogar-linea-blanca/hogar-lineablanca-lavadoras.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '10', 'url'=> 'https://www.fastshop.com.br/loja/eletrodomesticos/pra-sua-lavanderia', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '29', 'url'=> 'https://www.garbarino.com/productos/lavado/4297', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>  '13', 'url'=> 'https://www.liverpool.com.mx/tienda/lavadoras/cat861227', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '35', 'url'=> 'https://www.panafoto.com/categorias/hogar.html?cat=171', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '23', 'url'=> 'https://www.paris.cl/tienda/es/paris/search/linea-blanca-lavado-secado-lavadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'32', 'url'=> 'https://www.ribeiro.com.ar/browse/heladeras-cocina-y-lavado-lavado/_/N-1korz5r', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'20', 'url'=> 'https://www.sams.com.mx/linea-blanca/lavadoras-y-secadoras', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'2', 'url'=> 'https://www.submarino.com.br/categoria/eletrodomesticos/maquina-de-lavar-e-tanquinho/maquina-de-lavar', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'38', 'url'=> 'https://www.tiendamonge.com/linea-blanca?specs=424', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=>'7', 'url'=> 'https://www.walmart.com.br/categoria/eletrodomesticos/lavanderia/?fq=C:144/7953/', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'3', 'loja_id'=>'24', 'url'=> 'https://www.abcdin.cl/tienda/es/abcdin/linea-blanca/refrigeradores#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=>'24', 'url'=> 'https://www.abcdin.cl/tienda/es/abcdin/celulares/smartphones#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=>'24', 'url'=> 'https://www.abcdin.cl/tienda/es/abcdin/tv-audio/televisores-video/televisores-led#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=>'24', 'url'=> 'https://www.abcdin.cl/tienda/es/abcdin/linea-blanca/lavado-secado#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>'26', 'url'=> 'http://www.alkosto.com/electro/neveras', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=>'26', 'url'=> 'http://www.alkosto.com/telefonos-celulares/celulares-libres', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=>'26', 'url'=> 'http://www.alkosto.com/tv', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=>'26', 'url'=> 'http://www.alkosto.com/tv/televisores', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=>'26', 'url'=> 'http://www.alkosto.com/electro/lavadoras/lavadoras', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>'16', 'url'=> 'https://www.amazon.com.mx/b/?node=16354941011','status'=>'', 'device'=>'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=>'16', 'url'=> 'https://www.amazon.com.mx/b/ref=s9_acss_bw_fb_lensmoun_b2/ref=s9_acss_bw_cg_wire1_1b1/ref=s9_acss_bw_cg_mxceti_1a1_w?_encoding=UTF8&node=9687460011&pf_rd_m=AVDBXBAVVSXLQ&pf_rd_s=merchandised-search-6&pf_rd_r=WVPDE7GV549QCC7FT578&pf_rd_t=101&pf_rd_p=214627', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=>'16', 'url'=> 'https://www.amazon.com.mx/b?ie=UTF8&node=9687950011', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=>'16', 'url'=> 'https://www.amazon.com.mx/b/?node=16354823011', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>'1', 'url'=> 'https://www.americanas.com.br/categoria/eletrodomesticos/geladeira-refrigerador/#/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=>'1', 'url'=> 'https://www.americanas.com.br/categoria/celulares-e-smartphones/smartphone', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=>'1', 'url'=> 'https://www.americanas.com.br/categoria/tv-e-home-theater/tv/tv-led', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=>'1', 'url'=> 'https://www.americanas.com.br/categoria/eletrodomesticos/maquina-de-lavar-e-tanquinho/maquina-de-lavar', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '4', 'url'=> 'http://www.bestbuy.com.mx/productos/hogar/refrigeradores.html?cat=1290', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '4', 'url'=> 'http://www.bestbuy.com.mx/productos/tablets-y-celulares/telefonos-celulares.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '4', 'url'=> 'http://www.bestbuy.com.mx/productos/tv-y-video/pantallas.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '4', 'url'=> 'http://www.bestbuy.com.mx/productos/hogar/lavadoras-y-secadoras.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>  '9', 'url'=> 'https://www.carrefour.com.br/refrigerar?crfint=m-links|eletrodomesticos|refrigerar|2|refrigerar|0', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '9', 'url'=> 'https://www.carrefour.com.br/celular-e-smartphone?termo=%3Arelevance&isGrid=true&sort=', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=>  '0', 'url'=> 'https://www.carrefour.com.br/dicas/tecnologia-e-eletronicos/celular-e-smartphone?crfint=hm-tlink|tecnologia-e-eletronicos|telefonia|4|celular-e-smartphone|1', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '9', 'url'=> 'https://www.carrefour.com.br/tv?termo=%3Arelevance&isGrid=true&sort=', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '9', 'url'=> 'https://www.carrefour.com.br/lavar-e-secar-roupa?crfint=m-links|eletrodomesticos|lavar-e-secar-roupa|3|lavar-e-secar-roupa|0', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>  '12', 'url'=> 'http://www.claroshop.com/categoria/16201/refrigeradores-y-congeladores/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '12', 'url'=> 'http://www.claroshop.com/categoria/16002/celulares/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=>  '12', 'url'=> 'http://www.claroshop.com/categoria/16197/lavadoras-y-secadoras/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=>  '39', 'url'=> 'http://www.comandato.com/electrodomesticos/refrigeracion?O=OrderByReleaseDateDESC', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=>  '39', 'url'=> 'http://www.comandato.com/tecnologia/telefonia/celulares', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=>  '39', 'url'=> 'http://www.comandato.com/tecnologia/television-y-video/televisores-led?O=OrderByReleaseDateDESC', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=>  '39', 'url'=> 'http://www.comandato.com/electrodomesticos/lavado-y-secado?O=OrderByReleaseDateDESC', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=>  '31', 'url'=> 'https://www.compumundo.com.ar/productos/smartphones-libres/3757', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=>  '31', 'url'=> 'https://www.compumundo.com.ar/productos/tv-proyectores/3801', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '31', 'url'=> 'https://www.compumundo.com.ar/productos/smartphones-libres/3757', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '31', 'url'=> 'https://www.compumundo.com.ar/productos/tv-proyectores/3801', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '8', 'url'=> 'http://m.ricardoeletro.com.br/Loja/Eletrodomesticos/Refrigerador/256-270', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '8', 'url'=> 'http://m.ricardoeletro.com.br/Loja/Celulares-e-Telefones/Smartphones/44-491', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '8', 'url'=> 'http://m.ricardoeletro.com.br/Loja/TV-e-Video/TV/108-4370', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '8', 'url'=> 'http://m.ricardoeletro.com.br/Loja/Eletrodomesticos/Lava-e-Seca/256-706', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '15', 'url'=> 'http://m.costco.com.mx/view/c/linea-blanca/linea-blanca-refrigeradores-y-congeladores/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '15', 'url'=> 'http://www.costco.com.mx/view/c/linea-blanca/linea-blanca-refrigeradores-y-congeladores/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '15', 'url'=> 'http://www.costco.com.mx/view/c/electronica/tv-y-video', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '15', 'url'=> 'http://www.costco.com.mx/view/c/electronica/tv-y-video/televisiones/4K', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '15', 'url'=> 'http://www.costco.com.mx/view/c/linea-blanca/linea-blanca-lavanderia/lavadoras', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '17', 'url'=> 'http://www.elpalaciodehierro.com/hogar/hogar-linea-blanca/hogar-lineablanca-refrigeradores.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/hogar/hogar-linea-blanca/hogar-lineablanca-refrigeradores.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '17', 'url'=> 'http://www.elpalaciodehierro.com/tecnologia/tecnologia-celulares.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/tecnologia/tecnologia-celulares.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/tecnologia/tecnologia-celulares.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/tecnologia/tecnologia-celulares.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '17', 'url'=> 'http://www.elpalaciodehierro.com/tecnologia/tecnologia-tvyvideo/tecnologia-tvyvideo-pantallas.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '17', 'url'=> 'http://www.elpalaciodehierro.com/hogar/hogar-linea-blanca/hogar-lineablanca-lavadoras.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '17', 'url'=> 'https://www.elpalaciodehierro.com/hogar/hogar-linea-blanca/hogar-lineablanca-lavadoras.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '27', 'url'=> 'http://www.exito.com/Electrohogar-Grandes_Electrodomesticos-Neveras/_/N-2ai7?showMoreIds=109170', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '27', 'url'=> 'http://www.exito.com/Tecnologia-Celulares_y_accesorios/_/N-2b5r', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '27', 'url'=> 'http://www.exito.com/browse/Tecnologia-TV_y_Video-Televisores/_/N-2csn', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '27', 'url'=> 'http://www.exito.com/Electrohogar-Grandes_Electrodomesticos-Lavadoras_y_Secadoras/_/N-2aie', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/Eletrodomesticos/GeladeiraeRefrigerador/?Filtro=C13_C14&nid=200579', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/TelefoneseCelulares/Smartphones/?Filtro=C38_C326&nid=200740', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/tvseacessorios/Televisores/?Filtro=C1_C2', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/Eletrodomesticos/maquinadelavar/?Filtro=C13_C24&nid=200577', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '36', 'url'=> 'http://www.gollotienda.com/productos/linea-blanca/refrigeracion/refrigeradoras.html', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '36', 'url'=> 'http://www.gollotienda.com/productos/telefonia/celulares.html', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '36', 'url'=> 'http://www.gollotienda.com/productos/pantallas/led.html', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '36', 'url'=> 'http://www.gollotienda.com/productos/linea-blanca/lavanderia/lavadoras.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '25', 'url'=> 'http://www.tiendasjumbo.co/electrodomesticos/refrigeraci%C3%B3n', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '25', 'url'=> 'http://www.tiendasjumbo.co/tecnologia/celulares-y-tablets/celulares', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '25', 'url'=> 'http://www.tiendasjumbo.co/tecnologia/televisores-y-video/televisores/tvs?ref=LandingTv', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '25', 'url'=> 'http://www.tiendasjumbo.co/electrodomesticos/lavadoras-y-secadoras', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '18', 'url'=> 'http://www.sears.com.mx/categoria/15523/refrigeracion/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '18', 'url'=> 'http://www.sears.com.mx/categoria/4550/telefonia/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '18', 'url'=> 'http://www.sears.com.mx/categoria/15466/pantallas/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '18', 'url'=> 'http://www.sears.com.mx/categoria/10667/lavado/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '30', 'url'=> 'http://www.fravega.com/heladeras-freezers-y-cavas', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '30', 'url'=> 'http://www.fravega.com/celulares/celulares-liberados', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '30', 'url'=> 'http://www.fravega.com/tv-y-video/tv', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '30', 'url'=> 'http://www.fravega.com/lavado', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '37', 'url'=> 'https://hifi.com.do/productos/34/price-asc', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '37', 'url'=> 'https://hifi.com.do/productos/15/price-asc', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '37', 'url'=> 'https://hifi.com.do/productos/4/price-asc','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '19', 'url'=>  'https://www.elektra.com.mx/linea-blanca/refrigeradores-y-congeladores/refrigeradores', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '19', 'url'=> 'https://www .elektra.com.mx/telefonia/celulares/desbloqueados', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '19', 'url'=> 'https://www.elektra.com.mx/electronica/tv-y-video','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '19', 'url'=> 'https://www.elektra.com.mx/linea-blanca/lavado-y-secado/lavadoras', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '20', 'url'=> 'https://www.sams.com.mx/linea-blanca/refrigeradores-y-congeladores','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '20', 'url'=> 'https://www.sams.com.mx/celulares-y-smartphones/celulares/celulares-desbloqueados/_/N-83g', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '20', 'url'=> 'https://www.sams.com.mx/electronica/pantallas', 'status'=>'', 'device'=>  'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '20', 'url'=>  'https://www.sams.com.mx/linea-blanca/lavadoras-y-secadoras','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '10', 'url'=> 'https://www.fastshop.com.br/loja/eletrodomesticos/pra-sua-cozinha/refrigerador-geladeira', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '10', 'url'=> 'https://www.fastshop.com.br/loja/eletrodomesticos/pra-sua-cozinha/refrigerador-geladeira','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '10', 'url'=> 'https://www.fastshop.com.br/loja/tv-e-video/tvs-', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'4', 'loja_id'=> '10','url'=>  'https://www.fastshop.com.br/loja/eletrodomesticos/pra-sua-lavanderia', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '2', 'url'=> 'https://www.submarino.com.br/categoria/eletrodomesticos/geladeira-refrigerador/#/','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '2', 'url'=> 'https://www.submarino.com.br/categoria/eletrodomesticos/geladeira-refrigerador/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '2', 'url'=> 'https://www.submarino.com.br/categoria/celulares-e-smartphones/smartphone','status'=>'', 'device'=>   'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '2', 'url'=> 'https://www.submarino.com.br/categoria/tv-e-home-theater/tv/tv-led', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '2', 'url'=> 'https://www.submarino.com.br/categoria/eletrodomesticos/maquina-de-lavar-e-tanquinho/maquina-de-lavar', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '13', 'url'=> 'https://www.liverpool.com.mx/tienda/refrigeradores/cat4170025', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '13', 'url'=> 'https://www.liverpool.com.mx/tienda/ver-todos-los-modelos/cat5070000', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '13', 'url'=> 'https://www.liverpool.com.mx/tienda/pantallas/cat480023', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '13', 'url'=> 'https://www.liverpool.com.mx/tienda/lavadoras/cat861227', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '13', 'url'=> 'https://www.liverpool.com.mx/tienda/lavadoras/cat861227', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '35', 'url'=> 'https://www.panafoto.com/categorias/hogar.html?cat=168', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '35', 'url'=> 'https://www.panafoto.com/categorias/tvs.html', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '35', 'url'=> 'https://www.panafoto.com/categorias/hogar.html?cat=171', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '32', 'url'=> 'https://www.ribeiro.com.ar/browse/Heladeras-Cocina-y-Lavado-Heladeras-Con-Freezer-No-frost/_/N-1kfjx94','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '32', 'url'=> 'https://www.ribeiro.com.ar/browse/celulares-celulares-libres/_/N-1vpfmld', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '32', 'url'=> 'https://www.ribeiro.com.ar/browse/televisores-audio-foto-y-video-televisores-smart-tv-led/_/N-13nn749', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '32', 'url'=> 'https://www.ribeiro.com.ar/browse/heladeras-cocina-y-lavado-lavado/_/N-1korz5r', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '28', 'url'=> 'http://www.falabella.com.co/falabella-co/category/cat1040982/Neveras', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '28', 'url'=> 'http://www.falabella.com.co/falabella-co/category/cat1660941/Celulares-Libres', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '28', 'url'=> 'http://www.falabella.com.co/falabella-co/category/cat1360963/Televisores', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '28', 'url'=> 'http://www.falabella.com.co/falabella-co/category/cat50714/Lavadoras', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat40754/Refrigeracion','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat40662/Lavado', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat760706/Smartphones', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat210477/Televisores', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '33', 'url'=> 'http://www.falabella.com.pe/falabella-pe/category/cat6370551/TV-LED', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '21', 'url'=> 'http://www.falabella.com/falabella-cl/category/cat4074/No-Frost', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '21', 'url'=> 'http://www.falabella.com/falabella-cl/category/cat720161/Smartphones', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '21', 'url'=> 'http://www.falabella.com/falabella-cl/category/cat1012/TV', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '21', 'url'=> 'http://www.falabella.com/falabella-cl/category/cat4060/Lavadoras','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '29', 'url'=> 'https://www.garbarino.com/productos/heladeras-y-freezers/4290', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '29', 'url'=> 'https://www.garbarino.com/productos/celulares-libres/4359', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '29', 'url'=> 'https://www.garbarino.com/productos/tv-led-y-smart-tv/4342', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '29', 'url'=> 'https://www.garbarino.com/productos/lavado/4297', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '23', 'url'=> 'https://www.paris.cl/tienda/es/paris/search/linea-blanca-refrigeracion-todos-los-refrigeradores', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '23', 'url'=> 'https://www.paris.cl/tienda/es/paris/search/electro-television-todas-las-tv','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '22', 'url'=> 'https://simple.ripley.cl/electrohogar/lavado-y-secado', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '23', 'url'=> 'https://www.paris.cl/tienda/es/paris/search/tecnologia-celulares-smartphones','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '23', 'url'=> 'https://www.paris.cl/tienda/es/paris/search/linea-blanca-lavado-secado-lavadoras', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '38', 'url'=> 'https://www.tiendamonge.com/linea-blanca?specs=428','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'4', 'loja_id'=> '38', 'url'=> 'https://www.tiendamonge.com/linea-blanca?specs=424','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'3', 'loja_id'=> '38', 'url'=> 'https://www.tiendamonge.com/linea-blanca?specs=428','status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '38', 'url'=> 'https://www.tiendamonge.com/telefonia?specs=409', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '38', 'url'=> 'https://www.tiendamonge.com/tv-y-video?specs=408', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '34', 'url'=> 'http://simple.ripley.com.pe/tv-y-video/televisores/ver-todo-tv', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'2', 'loja_id'=> '4', 'url'=> 'http://www.bestbuy.com.mx/productos/tv-y-video/pantallas.html', 'status'=>'', 'device'=> 'Desktop'],
            ['categoria_id'=>'2', 'loja_id'=> '12', 'url'=> 'http://www.claroshop.com/categoria/16023/pantallas/', 'status'=>'', 'device'=> 'Mobile'],
            ['categoria_id'=>'1', 'loja_id'=> '5', 'url'=> 'http://www.extra.com.br/TelefoneseCelulares/Smartphones/?Filtro=C38_C326&nid=200740', 'status'=>'', 'device'=>  'Desktop'],
        ]);
    }
}
